//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public long ActivityId { get; set; }
        public string ActivityType { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> Activitydate { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Remarks { get; set; }
        public int OrganizationId { get; set; }
    }
}
