//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LFZ_TruckParkEntities : DbContext
    {
        public LFZ_TruckParkEntities()
            : base("name=LFZ_TruckParkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public virtual DbSet<M_APIKey> M_APIKey { get; set; }
        public virtual DbSet<M_Country> M_Country { get; set; }
        public virtual DbSet<M_ListOfValues> M_ListOfValues { get; set; }
        public virtual DbSet<M_Modules> M_Modules { get; set; }
        public virtual DbSet<M_RateSlab> M_RateSlab { get; set; }
        public virtual DbSet<M_Role> M_Role { get; set; }
        public virtual DbSet<M_TruckCapacity> M_TruckCapacity { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<ProformaInvoice> ProformaInvoices { get; set; }
        public virtual DbSet<ProformaInvoiceDet> ProformaInvoiceDets { get; set; }
        public virtual DbSet<Truck> Trucks { get; set; }
        public virtual DbSet<TruckDetail> TruckDetails { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<Map_Ent2Ent> Map_Ent2Ent { get; set; }
        public virtual DbSet<Map_RoleModule> Map_RoleModule { get; set; }
        public virtual DbSet<Map_UserRole> Map_UserRole { get; set; }
        public virtual DbSet<ProformaInvoiceB4Clean> ProformaInvoiceB4Clean { get; set; }
        public virtual DbSet<ProformaInvoiceDetB4Clean> ProformaInvoiceDetB4Clean { get; set; }
        public virtual DbSet<TruckDetailsB4Cleanup> TruckDetailsB4Cleanup { get; set; }
        public virtual DbSet<M_ExtAPI_ReceivedLog> M_ExtAPI_ReceivedLog { get; set; }
        public virtual DbSet<M_ExtAPI_SentLog> M_ExtAPI_SentLog { get; set; }
    
        public virtual ObjectResult<BillableTrucks_G_Result> BillableTrucks_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BillableTrucks_G_Result>("BillableTrucks_G");
        }
    
        public virtual ObjectResult<CheckTruckStatus_G_Result> CheckTruckStatus_G(string truckNo)
        {
            var truckNoParameter = truckNo != null ?
                new ObjectParameter("TruckNo", truckNo) :
                new ObjectParameter("TruckNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckTruckStatus_G_Result>("CheckTruckStatus_G", truckNoParameter);
        }
    
        public virtual int CREATEMODEL(string tableName, string cLASSNAME)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var cLASSNAMEParameter = cLASSNAME != null ?
                new ObjectParameter("CLASSNAME", cLASSNAME) :
                new ObjectParameter("CLASSNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATEMODEL", tableNameParameter, cLASSNAMEParameter);
        }
    
        public virtual ObjectResult<Dashboard_G_Result> Dashboard_G(Nullable<int> roleId, Nullable<int> uDID, Nullable<int> orgId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            var orgIdParameter = orgId.HasValue ?
                new ObjectParameter("OrgId", orgId) :
                new ObjectParameter("OrgId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dashboard_G_Result>("Dashboard_G", roleIdParameter, uDIDParameter, orgIdParameter);
        }
    
        [DbFunction("LFZ_TruckParkEntities", "GetGroupUsers")]
        public virtual IQueryable<Nullable<int>> GetGroupUsers(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<int>>("[LFZ_TruckParkEntities].[GetGroupUsers](@UDID)", uDIDParameter);
        }
    
        public virtual ObjectResult<GetMappingModulesByRoleId_Result> GetMappingModulesByRoleId(Nullable<int> roleid)
        {
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("Roleid", roleid) :
                new ObjectParameter("Roleid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMappingModulesByRoleId_Result>("GetMappingModulesByRoleId", roleidParameter);
        }
    
        public virtual ObjectResult<GetMenusBasedRoleById_G_Result> GetMenusBasedRoleById_G(Nullable<int> udid)
        {
            var udidParameter = udid.HasValue ?
                new ObjectParameter("udid", udid) :
                new ObjectParameter("udid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMenusBasedRoleById_G_Result>("GetMenusBasedRoleById_G", udidParameter);
        }
    
        public virtual int HospitalList_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HospitalList_G");
        }
    
        public virtual ObjectResult<InvoiceDetails_API_G_Result> InvoiceDetails_API_G(Nullable<int> proformaInvoiceId)
        {
            var proformaInvoiceIdParameter = proformaInvoiceId.HasValue ?
                new ObjectParameter("ProformaInvoiceId", proformaInvoiceId) :
                new ObjectParameter("ProformaInvoiceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InvoiceDetails_API_G_Result>("InvoiceDetails_API_G", proformaInvoiceIdParameter);
        }
    
        public virtual ObjectResult<M_Country_G_Result> M_Country_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_Country_G_Result>("M_Country_G");
        }
    
        public virtual ObjectResult<M_LOV_G_Result> M_LOV_G(Nullable<int> lOVId)
        {
            var lOVIdParameter = lOVId.HasValue ?
                new ObjectParameter("LOVId", lOVId) :
                new ObjectParameter("LOVId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_LOV_G_Result>("M_LOV_G", lOVIdParameter);
        }
    
        public virtual ObjectResult<M_UserDetails_G_Result> M_UserDetails_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M_UserDetails_G_Result>("M_UserDetails_G");
        }
    
        public virtual int Organization_CRUD(Nullable<short> flag, string companyName, string companyShortName, Nullable<short> organizationTypeId, Nullable<int> organizationID, string organizationIDList, ObjectParameter outError)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(short));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var companyShortNameParameter = companyShortName != null ?
                new ObjectParameter("CompanyShortName", companyShortName) :
                new ObjectParameter("CompanyShortName", typeof(string));
    
            var organizationTypeIdParameter = organizationTypeId.HasValue ?
                new ObjectParameter("OrganizationTypeId", organizationTypeId) :
                new ObjectParameter("OrganizationTypeId", typeof(short));
    
            var organizationIDParameter = organizationID.HasValue ?
                new ObjectParameter("OrganizationID", organizationID) :
                new ObjectParameter("OrganizationID", typeof(int));
    
            var organizationIDListParameter = organizationIDList != null ?
                new ObjectParameter("OrganizationIDList", organizationIDList) :
                new ObjectParameter("OrganizationIDList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Organization_CRUD", flagParameter, companyNameParameter, companyShortNameParameter, organizationTypeIdParameter, organizationIDParameter, organizationIDListParameter, outError);
        }
    
        public virtual ObjectResult<Organization_G_Result> Organization_G(Nullable<int> organizationId)
        {
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Organization_G_Result>("Organization_G", organizationIdParameter);
        }
    
        public virtual ObjectResult<OrganizationEntToEnt_G_Result> OrganizationEntToEnt_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrganizationEntToEnt_G_Result>("OrganizationEntToEnt_G", uDIDParameter);
        }
    
        public virtual ObjectResult<OrganizationMailId_G_Result> OrganizationMailId_G(string truckDetailsIdList)
        {
            var truckDetailsIdListParameter = truckDetailsIdList != null ?
                new ObjectParameter("TruckDetailsIdList", truckDetailsIdList) :
                new ObjectParameter("TruckDetailsIdList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrganizationMailId_G_Result>("OrganizationMailId_G", truckDetailsIdListParameter);
        }
    
        public virtual int ProfomaInvoice_U(Nullable<int> invoiceId, string path)
        {
            var invoiceIdParameter = invoiceId.HasValue ?
                new ObjectParameter("InvoiceId", invoiceId) :
                new ObjectParameter("InvoiceId", typeof(int));
    
            var pathParameter = path != null ?
                new ObjectParameter("path", path) :
                new ObjectParameter("path", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProfomaInvoice_U", invoiceIdParameter, pathParameter);
        }
    
        public virtual int ProformaInvoice_C(Nullable<int> uDID, Nullable<int> organizationId, Nullable<int> totalTruckCount, string truckIdList, ObjectParameter outParam)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            var totalTruckCountParameter = totalTruckCount.HasValue ?
                new ObjectParameter("TotalTruckCount", totalTruckCount) :
                new ObjectParameter("TotalTruckCount", typeof(int));
    
            var truckIdListParameter = truckIdList != null ?
                new ObjectParameter("TruckIdList", truckIdList) :
                new ObjectParameter("TruckIdList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProformaInvoice_C", uDIDParameter, organizationIdParameter, totalTruckCountParameter, truckIdListParameter, outParam);
        }
    
        public virtual ObjectResult<ProformaInvoice_G_Result> ProformaInvoice_G(Nullable<int> proformainvoiceid)
        {
            var proformainvoiceidParameter = proformainvoiceid.HasValue ?
                new ObjectParameter("proformainvoiceid", proformainvoiceid) :
                new ObjectParameter("proformainvoiceid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProformaInvoice_G_Result>("ProformaInvoice_G", proformainvoiceidParameter);
        }
    
        public virtual ObjectResult<proformaInvoiceDetails_G_Result> proformaInvoiceDetails_G(Nullable<int> proformainvoiceid)
        {
            var proformainvoiceidParameter = proformainvoiceid.HasValue ?
                new ObjectParameter("proformainvoiceid", proformainvoiceid) :
                new ObjectParameter("proformainvoiceid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proformaInvoiceDetails_G_Result>("proformaInvoiceDetails_G", proformainvoiceidParameter);
        }
    
        public virtual ObjectResult<ProformaInvoiceList_G_Result> ProformaInvoiceList_G(Nullable<int> roleId, Nullable<int> uDID)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProformaInvoiceList_G_Result>("ProformaInvoiceList_G", roleIdParameter, uDIDParameter);
        }
    
        public virtual ObjectResult<Role_G_Result> Role_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Role_G_Result>("Role_G");
        }
    
        public virtual ObjectResult<Scheduler_Admin_Result> Scheduler_Admin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Scheduler_Admin_Result>("Scheduler_Admin");
        }
    
        public virtual ObjectResult<Scheduler_Admin_ISMAIL_Result> Scheduler_Admin_ISMAIL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Scheduler_Admin_ISMAIL_Result>("Scheduler_Admin_ISMAIL");
        }
    
        public virtual ObjectResult<Scheduler_Admin_old_Result> Scheduler_Admin_old()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Scheduler_Admin_old_Result>("Scheduler_Admin_old");
        }
    
        public virtual ObjectResult<Scheduler_Admin_test_Result> Scheduler_Admin_test()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Scheduler_Admin_test_Result>("Scheduler_Admin_test");
        }
    
        public virtual ObjectResult<Scheduler_Enterprise_Result> Scheduler_Enterprise(Nullable<int> organisationId)
        {
            var organisationIdParameter = organisationId.HasValue ?
                new ObjectParameter("OrganisationId", organisationId) :
                new ObjectParameter("OrganisationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Scheduler_Enterprise_Result>("Scheduler_Enterprise", organisationIdParameter);
        }
    
        public virtual ObjectResult<Scheduler_Enterprise_old_Result> Scheduler_Enterprise_old(Nullable<int> organisationId)
        {
            var organisationIdParameter = organisationId.HasValue ?
                new ObjectParameter("OrganisationId", organisationId) :
                new ObjectParameter("OrganisationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Scheduler_Enterprise_old_Result>("Scheduler_Enterprise_old", organisationIdParameter);
        }
    
        [DbFunction("LFZ_TruckParkEntities", "Split")]
        public virtual IQueryable<string> Split(string inputString, string delimiter)
        {
            var inputStringParameter = inputString != null ?
                new ObjectParameter("InputString", inputString) :
                new ObjectParameter("InputString", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[LFZ_TruckParkEntities].[Split](@InputString, @Delimiter)", inputStringParameter, delimiterParameter);
        }
    
        public virtual int Truck_CRUD(Nullable<int> truckId, string truckNo, Nullable<int> ownedByOrganizationId, Nullable<int> truckCapacityId, Nullable<int> uDID, Nullable<int> calledByOrganizationId, Nullable<System.DateTime> expectedArrivalDate, Nullable<System.DateTime> expectedDepatureDate, Nullable<int> localTransferTypeId, string transportName, string transportNo, string driverName, string driverNo, Nullable<int> materialTypeId, string materialGoods, Nullable<System.DateTime> actualArrivalDate, Nullable<System.DateTime> actualDepatureDate, Nullable<bool> isForecasted, Nullable<bool> isCheckedIn, Nullable<bool> isCalledOut, ObjectParameter outId, Nullable<int> truckDetailsId, Nullable<int> flag)
        {
            var truckIdParameter = truckId.HasValue ?
                new ObjectParameter("TruckId", truckId) :
                new ObjectParameter("TruckId", typeof(int));
    
            var truckNoParameter = truckNo != null ?
                new ObjectParameter("TruckNo", truckNo) :
                new ObjectParameter("TruckNo", typeof(string));
    
            var ownedByOrganizationIdParameter = ownedByOrganizationId.HasValue ?
                new ObjectParameter("OwnedByOrganizationId", ownedByOrganizationId) :
                new ObjectParameter("OwnedByOrganizationId", typeof(int));
    
            var truckCapacityIdParameter = truckCapacityId.HasValue ?
                new ObjectParameter("TruckCapacityId", truckCapacityId) :
                new ObjectParameter("TruckCapacityId", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            var calledByOrganizationIdParameter = calledByOrganizationId.HasValue ?
                new ObjectParameter("CalledByOrganizationId", calledByOrganizationId) :
                new ObjectParameter("CalledByOrganizationId", typeof(int));
    
            var expectedArrivalDateParameter = expectedArrivalDate.HasValue ?
                new ObjectParameter("ExpectedArrivalDate", expectedArrivalDate) :
                new ObjectParameter("ExpectedArrivalDate", typeof(System.DateTime));
    
            var expectedDepatureDateParameter = expectedDepatureDate.HasValue ?
                new ObjectParameter("ExpectedDepatureDate", expectedDepatureDate) :
                new ObjectParameter("ExpectedDepatureDate", typeof(System.DateTime));
    
            var localTransferTypeIdParameter = localTransferTypeId.HasValue ?
                new ObjectParameter("LocalTransferTypeId", localTransferTypeId) :
                new ObjectParameter("LocalTransferTypeId", typeof(int));
    
            var transportNameParameter = transportName != null ?
                new ObjectParameter("TransportName", transportName) :
                new ObjectParameter("TransportName", typeof(string));
    
            var transportNoParameter = transportNo != null ?
                new ObjectParameter("TransportNo", transportNo) :
                new ObjectParameter("TransportNo", typeof(string));
    
            var driverNameParameter = driverName != null ?
                new ObjectParameter("DriverName", driverName) :
                new ObjectParameter("DriverName", typeof(string));
    
            var driverNoParameter = driverNo != null ?
                new ObjectParameter("DriverNo", driverNo) :
                new ObjectParameter("DriverNo", typeof(string));
    
            var materialTypeIdParameter = materialTypeId.HasValue ?
                new ObjectParameter("MaterialTypeId", materialTypeId) :
                new ObjectParameter("MaterialTypeId", typeof(int));
    
            var materialGoodsParameter = materialGoods != null ?
                new ObjectParameter("MaterialGoods", materialGoods) :
                new ObjectParameter("MaterialGoods", typeof(string));
    
            var actualArrivalDateParameter = actualArrivalDate.HasValue ?
                new ObjectParameter("ActualArrivalDate", actualArrivalDate) :
                new ObjectParameter("ActualArrivalDate", typeof(System.DateTime));
    
            var actualDepatureDateParameter = actualDepatureDate.HasValue ?
                new ObjectParameter("ActualDepatureDate", actualDepatureDate) :
                new ObjectParameter("ActualDepatureDate", typeof(System.DateTime));
    
            var isForecastedParameter = isForecasted.HasValue ?
                new ObjectParameter("IsForecasted", isForecasted) :
                new ObjectParameter("IsForecasted", typeof(bool));
    
            var isCheckedInParameter = isCheckedIn.HasValue ?
                new ObjectParameter("IsCheckedIn", isCheckedIn) :
                new ObjectParameter("IsCheckedIn", typeof(bool));
    
            var isCalledOutParameter = isCalledOut.HasValue ?
                new ObjectParameter("IsCalledOut", isCalledOut) :
                new ObjectParameter("IsCalledOut", typeof(bool));
    
            var truckDetailsIdParameter = truckDetailsId.HasValue ?
                new ObjectParameter("TruckDetailsId", truckDetailsId) :
                new ObjectParameter("TruckDetailsId", typeof(int));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Truck_CRUD", truckIdParameter, truckNoParameter, ownedByOrganizationIdParameter, truckCapacityIdParameter, uDIDParameter, calledByOrganizationIdParameter, expectedArrivalDateParameter, expectedDepatureDateParameter, localTransferTypeIdParameter, transportNameParameter, transportNoParameter, driverNameParameter, driverNoParameter, materialTypeIdParameter, materialGoodsParameter, actualArrivalDateParameter, actualDepatureDateParameter, isForecastedParameter, isCheckedInParameter, isCalledOutParameter, outId, truckDetailsIdParameter, flagParameter);
        }
    
        public virtual ObjectResult<Truck_G_Result> Truck_G(string truckNo)
        {
            var truckNoParameter = truckNo != null ?
                new ObjectParameter("TruckNo", truckNo) :
                new ObjectParameter("TruckNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Truck_G_Result>("Truck_G", truckNoParameter);
        }
    
        public virtual ObjectResult<TruckCalledOutList_G_Result> TruckCalledOutList_G(Nullable<int> roleId, Nullable<int> uDID, Nullable<int> organizationId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TruckCalledOutList_G_Result>("TruckCalledOutList_G", roleIdParameter, uDIDParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<TruckCapacity_G_Result> TruckCapacity_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TruckCapacity_G_Result>("TruckCapacity_G");
        }
    
        public virtual ObjectResult<TruckCheckedInList_G_Result> TruckCheckedInList_G(Nullable<int> roleId, Nullable<int> uDID, Nullable<int> organizationId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TruckCheckedInList_G_Result>("TruckCheckedInList_G", roleIdParameter, uDIDParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<TruckCheckedOutList_G_Result> TruckCheckedOutList_G(Nullable<int> roleId, Nullable<int> uDID, Nullable<int> organizationId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TruckCheckedOutList_G_Result>("TruckCheckedOutList_G", roleIdParameter, uDIDParameter, organizationIdParameter);
        }
    
        public virtual ObjectResult<TruckDetails_G_Result> TruckDetails_G(Nullable<int> truckDetailsId)
        {
            var truckDetailsIdParameter = truckDetailsId.HasValue ?
                new ObjectParameter("TruckDetailsId", truckDetailsId) :
                new ObjectParameter("TruckDetailsId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TruckDetails_G_Result>("TruckDetails_G", truckDetailsIdParameter);
        }
    
        public virtual ObjectResult<TruckList_G_Result> TruckList_G(Nullable<int> roleId, Nullable<int> uDID, Nullable<int> organizationId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            var organizationIdParameter = organizationId.HasValue ?
                new ObjectParameter("OrganizationId", organizationId) :
                new ObjectParameter("OrganizationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TruckList_G_Result>("TruckList_G", roleIdParameter, uDIDParameter, organizationIdParameter);
        }
    
        public virtual int TruckStatus_U(string truckDetailsIdList, Nullable<byte> flag, Nullable<int> uDID, ObjectParameter outError)
        {
            var truckDetailsIdListParameter = truckDetailsIdList != null ?
                new ObjectParameter("TruckDetailsIdList", truckDetailsIdList) :
                new ObjectParameter("TruckDetailsIdList", typeof(string));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TruckStatus_U", truckDetailsIdListParameter, flagParameter, uDIDParameter, outError);
        }
    
        public virtual int UserChangePassword(Nullable<int> uDID, string password, string saltKey, ObjectParameter outError)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var saltKeyParameter = saltKey != null ?
                new ObjectParameter("SaltKey", saltKey) :
                new ObjectParameter("SaltKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserChangePassword", uDIDParameter, passwordParameter, saltKeyParameter, outError);
        }
    
        public virtual int UserCreation_CRUD(Nullable<int> udid, Nullable<int> organizationID, string employeeName, string password, Nullable<int> roleId, Nullable<int> reportingToId, Nullable<int> departmentId, string emailId, string mobileNo, Nullable<int> createdBy, Nullable<bool> isActive, Nullable<byte> flag, ObjectParameter outError, string saltKey)
        {
            var udidParameter = udid.HasValue ?
                new ObjectParameter("udid", udid) :
                new ObjectParameter("udid", typeof(int));
    
            var organizationIDParameter = organizationID.HasValue ?
                new ObjectParameter("OrganizationID", organizationID) :
                new ObjectParameter("OrganizationID", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var reportingToIdParameter = reportingToId.HasValue ?
                new ObjectParameter("ReportingToId", reportingToId) :
                new ObjectParameter("ReportingToId", typeof(int));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(byte));
    
            var saltKeyParameter = saltKey != null ?
                new ObjectParameter("SaltKey", saltKey) :
                new ObjectParameter("SaltKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserCreation_CRUD", udidParameter, organizationIDParameter, employeeNameParameter, passwordParameter, roleIdParameter, reportingToIdParameter, departmentIdParameter, emailIdParameter, mobileNoParameter, createdByParameter, isActiveParameter, flagParameter, outError, saltKeyParameter);
        }
    
        public virtual int UserCreation_D(Nullable<int> uDID, ObjectParameter outError)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserCreation_D", uDIDParameter, outError);
        }
    
        public virtual ObjectResult<UserCreation_G_Result> UserCreation_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserCreation_G_Result>("UserCreation_G", uDIDParameter);
        }
    
        public virtual ObjectResult<UserCreationList_G_Result> UserCreationList_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserCreationList_G_Result>("UserCreationList_G");
        }
    
        public virtual ObjectResult<Userdetails_G_Result> Userdetails_G(Nullable<int> uDID)
        {
            var uDIDParameter = uDID.HasValue ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Userdetails_G_Result>("Userdetails_G", uDIDParameter);
        }
    
        public virtual int UserLogin(string emailId, string password, ObjectParameter outError)
        {
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserLogin", emailIdParameter, passwordParameter, outError);
        }
    
        public virtual ObjectResult<usp_AdminEnterpiseDetails_G_Result> usp_AdminEnterpiseDetails_G()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AdminEnterpiseDetails_G_Result>("usp_AdminEnterpiseDetails_G");
        }
    
        public virtual ObjectResult<ValidateUser_OnePortal_Result> ValidateUser_OnePortal(string emailid)
        {
            var emailidParameter = emailid != null ?
                new ObjectParameter("Emailid", emailid) :
                new ObjectParameter("Emailid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidateUser_OnePortal_Result>("ValidateUser_OnePortal", emailidParameter);
        }
    
        public virtual int API_ReceivedLog(Nullable<int> apiKeyId, string payLoad, string sourceIP)
        {
            var apiKeyIdParameter = apiKeyId.HasValue ?
                new ObjectParameter("ApiKeyId", apiKeyId) :
                new ObjectParameter("ApiKeyId", typeof(int));
    
            var payLoadParameter = payLoad != null ?
                new ObjectParameter("PayLoad", payLoad) :
                new ObjectParameter("PayLoad", typeof(string));
    
            var sourceIPParameter = sourceIP != null ?
                new ObjectParameter("SourceIP", sourceIP) :
                new ObjectParameter("SourceIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("API_ReceivedLog", apiKeyIdParameter, payLoadParameter, sourceIPParameter);
        }
    
        public virtual int API_SentLog(string payLoad, string sourceIP)
        {
            var payLoadParameter = payLoad != null ?
                new ObjectParameter("PayLoad", payLoad) :
                new ObjectParameter("PayLoad", typeof(string));
    
            var sourceIPParameter = sourceIP != null ?
                new ObjectParameter("SourceIP", sourceIP) :
                new ObjectParameter("SourceIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("API_SentLog", payLoadParameter, sourceIPParameter);
        }
    
        public virtual int EcallUp_CU(string gUID, string companyGUID, string companyName, string userGUID, string truckGUID, string driverGUID, string preGateGUID, string preGateName, string parkGUID, string parkName, string parkType, string terminalGUID, string terminalName, string categoryGUID, string categoryName, string portGUID, string portName, string portType, string statuses, string materialType, string transferType, string status, Nullable<System.DateTime> estArrivalDateTime, Nullable<System.DateTime> departureDate, Nullable<System.DateTime> createdAt, Nullable<System.DateTime> updatedAt, ObjectParameter outIsSuccess, ObjectParameter outMessage)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(string));
    
            var companyGUIDParameter = companyGUID != null ?
                new ObjectParameter("CompanyGUID", companyGUID) :
                new ObjectParameter("CompanyGUID", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(string));
    
            var truckGUIDParameter = truckGUID != null ?
                new ObjectParameter("TruckGUID", truckGUID) :
                new ObjectParameter("TruckGUID", typeof(string));
    
            var driverGUIDParameter = driverGUID != null ?
                new ObjectParameter("DriverGUID", driverGUID) :
                new ObjectParameter("DriverGUID", typeof(string));
    
            var preGateGUIDParameter = preGateGUID != null ?
                new ObjectParameter("PreGateGUID", preGateGUID) :
                new ObjectParameter("PreGateGUID", typeof(string));
    
            var preGateNameParameter = preGateName != null ?
                new ObjectParameter("PreGateName", preGateName) :
                new ObjectParameter("PreGateName", typeof(string));
    
            var parkGUIDParameter = parkGUID != null ?
                new ObjectParameter("ParkGUID", parkGUID) :
                new ObjectParameter("ParkGUID", typeof(string));
    
            var parkNameParameter = parkName != null ?
                new ObjectParameter("ParkName", parkName) :
                new ObjectParameter("ParkName", typeof(string));
    
            var parkTypeParameter = parkType != null ?
                new ObjectParameter("ParkType", parkType) :
                new ObjectParameter("ParkType", typeof(string));
    
            var terminalGUIDParameter = terminalGUID != null ?
                new ObjectParameter("TerminalGUID", terminalGUID) :
                new ObjectParameter("TerminalGUID", typeof(string));
    
            var terminalNameParameter = terminalName != null ?
                new ObjectParameter("TerminalName", terminalName) :
                new ObjectParameter("TerminalName", typeof(string));
    
            var categoryGUIDParameter = categoryGUID != null ?
                new ObjectParameter("CategoryGUID", categoryGUID) :
                new ObjectParameter("CategoryGUID", typeof(string));
    
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            var portGUIDParameter = portGUID != null ?
                new ObjectParameter("PortGUID", portGUID) :
                new ObjectParameter("PortGUID", typeof(string));
    
            var portNameParameter = portName != null ?
                new ObjectParameter("PortName", portName) :
                new ObjectParameter("PortName", typeof(string));
    
            var portTypeParameter = portType != null ?
                new ObjectParameter("PortType", portType) :
                new ObjectParameter("PortType", typeof(string));
    
            var statusesParameter = statuses != null ?
                new ObjectParameter("Statuses", statuses) :
                new ObjectParameter("Statuses", typeof(string));
    
            var materialTypeParameter = materialType != null ?
                new ObjectParameter("MaterialType", materialType) :
                new ObjectParameter("MaterialType", typeof(string));
    
            var transferTypeParameter = transferType != null ?
                new ObjectParameter("TransferType", transferType) :
                new ObjectParameter("TransferType", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var estArrivalDateTimeParameter = estArrivalDateTime.HasValue ?
                new ObjectParameter("EstArrivalDateTime", estArrivalDateTime) :
                new ObjectParameter("EstArrivalDateTime", typeof(System.DateTime));
    
            var departureDateParameter = departureDate.HasValue ?
                new ObjectParameter("DepartureDate", departureDate) :
                new ObjectParameter("DepartureDate", typeof(System.DateTime));
    
            var createdAtParameter = createdAt.HasValue ?
                new ObjectParameter("CreatedAt", createdAt) :
                new ObjectParameter("CreatedAt", typeof(System.DateTime));
    
            var updatedAtParameter = updatedAt.HasValue ?
                new ObjectParameter("UpdatedAt", updatedAt) :
                new ObjectParameter("UpdatedAt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EcallUp_CU", gUIDParameter, companyGUIDParameter, companyNameParameter, userGUIDParameter, truckGUIDParameter, driverGUIDParameter, preGateGUIDParameter, preGateNameParameter, parkGUIDParameter, parkNameParameter, parkTypeParameter, terminalGUIDParameter, terminalNameParameter, categoryGUIDParameter, categoryNameParameter, portGUIDParameter, portNameParameter, portTypeParameter, statusesParameter, materialTypeParameter, transferTypeParameter, statusParameter, estArrivalDateTimeParameter, departureDateParameter, createdAtParameter, updatedAtParameter, outIsSuccess, outMessage);
        }
    
        public virtual int IsTruckExists(string truckNo, string gUID, string ownedByOrgGUID, string truckCapacityGUID, string changedByGUID, ObjectParameter outMssg)
        {
            var truckNoParameter = truckNo != null ?
                new ObjectParameter("TruckNo", truckNo) :
                new ObjectParameter("TruckNo", typeof(string));
    
            var gUIDParameter = gUID != null ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(string));
    
            var ownedByOrgGUIDParameter = ownedByOrgGUID != null ?
                new ObjectParameter("OwnedByOrgGUID", ownedByOrgGUID) :
                new ObjectParameter("OwnedByOrgGUID", typeof(string));
    
            var truckCapacityGUIDParameter = truckCapacityGUID != null ?
                new ObjectParameter("TruckCapacityGUID", truckCapacityGUID) :
                new ObjectParameter("TruckCapacityGUID", typeof(string));
    
            var changedByGUIDParameter = changedByGUID != null ?
                new ObjectParameter("ChangedByGUID", changedByGUID) :
                new ObjectParameter("ChangedByGUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IsTruckExists", truckNoParameter, gUIDParameter, ownedByOrgGUIDParameter, truckCapacityGUIDParameter, changedByGUIDParameter, outMssg);
        }
    
        public virtual int Truck_CRUD_API(string gUID, string truckGUID, string truckNo, string calledByOrgGUID, string truckCapacity, Nullable<System.DateTime> expectedArrivalDate, Nullable<System.DateTime> expectedDepatureDate, string transferType, string transportName, string transportNo, string driverName, string driverNo, string materialType, string uDID, ObjectParameter outId, ObjectParameter outMssg, ObjectParameter outIsSuccess)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(string));
    
            var truckGUIDParameter = truckGUID != null ?
                new ObjectParameter("TruckGUID", truckGUID) :
                new ObjectParameter("TruckGUID", typeof(string));
    
            var truckNoParameter = truckNo != null ?
                new ObjectParameter("TruckNo", truckNo) :
                new ObjectParameter("TruckNo", typeof(string));
    
            var calledByOrgGUIDParameter = calledByOrgGUID != null ?
                new ObjectParameter("CalledByOrgGUID", calledByOrgGUID) :
                new ObjectParameter("CalledByOrgGUID", typeof(string));
    
            var truckCapacityParameter = truckCapacity != null ?
                new ObjectParameter("TruckCapacity", truckCapacity) :
                new ObjectParameter("TruckCapacity", typeof(string));
    
            var expectedArrivalDateParameter = expectedArrivalDate.HasValue ?
                new ObjectParameter("ExpectedArrivalDate", expectedArrivalDate) :
                new ObjectParameter("ExpectedArrivalDate", typeof(System.DateTime));
    
            var expectedDepatureDateParameter = expectedDepatureDate.HasValue ?
                new ObjectParameter("ExpectedDepatureDate", expectedDepatureDate) :
                new ObjectParameter("ExpectedDepatureDate", typeof(System.DateTime));
    
            var transferTypeParameter = transferType != null ?
                new ObjectParameter("TransferType", transferType) :
                new ObjectParameter("TransferType", typeof(string));
    
            var transportNameParameter = transportName != null ?
                new ObjectParameter("TransportName", transportName) :
                new ObjectParameter("TransportName", typeof(string));
    
            var transportNoParameter = transportNo != null ?
                new ObjectParameter("TransportNo", transportNo) :
                new ObjectParameter("TransportNo", typeof(string));
    
            var driverNameParameter = driverName != null ?
                new ObjectParameter("DriverName", driverName) :
                new ObjectParameter("DriverName", typeof(string));
    
            var driverNoParameter = driverNo != null ?
                new ObjectParameter("DriverNo", driverNo) :
                new ObjectParameter("DriverNo", typeof(string));
    
            var materialTypeParameter = materialType != null ?
                new ObjectParameter("MaterialType", materialType) :
                new ObjectParameter("MaterialType", typeof(string));
    
            var uDIDParameter = uDID != null ?
                new ObjectParameter("UDID", uDID) :
                new ObjectParameter("UDID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Truck_CRUD_API", gUIDParameter, truckGUIDParameter, truckNoParameter, calledByOrgGUIDParameter, truckCapacityParameter, expectedArrivalDateParameter, expectedDepatureDateParameter, transferTypeParameter, transportNameParameter, transportNoParameter, driverNameParameter, driverNoParameter, materialTypeParameter, uDIDParameter, outId, outMssg, outIsSuccess);
        }
    }
}
