//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ExtAPI_ReceivedLog
    {
        public int LogId { get; set; }
        public Nullable<int> APIKeyId { get; set; }
        public string PayLoad { get; set; }
        public string SourceIP { get; set; }
        public System.DateTime ReceivedAt { get; set; }
    }
}
