//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Modules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_Modules()
        {
            this.Map_RoleModule = new HashSet<Map_RoleModule>();
            this.Map_RoleModule1 = new HashSet<Map_RoleModule>();
        }
    
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> Parentid { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public bool IsActive { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public string IconImage { get; set; }
        public int OrganizationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Map_RoleModule> Map_RoleModule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Map_RoleModule> Map_RoleModule1 { get; set; }
    }
}
