//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public short OrganizationID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyShortName { get; set; }
        public Nullable<System.DateTime> OrganizationCreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public short OrganizationTypeId { get; set; }
        public string CompanyAddress { get; set; }
    }
}
