//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProformaInvoiceB4Clean
    {
        public long ProformaInvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public int OrganizationId { get; set; }
        public Nullable<int> TotalTruckCount { get; set; }
        public Nullable<decimal> TotalInvoiceAmount { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public System.DateTime Invoicedate { get; set; }
        public string InvoiceFilePath { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public bool IsActive { get; set; }
    }
}
