//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProformaInvoiceDet
    {
        public long ProformaInvoiceDetId { get; set; }
        public long ProformaInvoiceId { get; set; }
        public string TruckNo { get; set; }
        public int TruckCapacityId { get; set; }
        public System.DateTime CheckedInDate { get; set; }
        public System.DateTime CheckedOutDate { get; set; }
        public decimal InvoiceRate { get; set; }
        public decimal InvoiceAmount { get; set; }
        public System.DateTime Invoicedate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public bool IsActive { get; set; }
    }
}
