//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckDetail
    {
        public long TruckDetailsId { get; set; }
        public long TruckId { get; set; }
        public int CalledByOrganizationId { get; set; }
        public int TruckCapacityId { get; set; }
        public Nullable<System.DateTime> ExpectedArrivalDate { get; set; }
        public Nullable<System.DateTime> ExpectedDepatureDate { get; set; }
        public int LocalTransferTypeId { get; set; }
        public string TransportName { get; set; }
        public string TransportNo { get; set; }
        public string DriverName { get; set; }
        public string DriverNo { get; set; }
        public Nullable<int> MaterialTypeId { get; set; }
        public string MaterialGoods { get; set; }
        public Nullable<System.DateTime> ActualArrivalDate { get; set; }
        public Nullable<System.DateTime> ActualDepatureDate { get; set; }
        public bool IsForecasted { get; set; }
        public bool IsCheckedIn { get; set; }
        public bool IsCalledOut { get; set; }
        public Nullable<bool> IsBilled { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public bool IsActive { get; set; }
    }
}
