//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        public long TruckId { get; set; }
        public string TruckNo { get; set; }
        public Nullable<int> OwnedByOrganizationId { get; set; }
        public Nullable<int> TruckCapacityId { get; set; }
        public Nullable<int> Createdby { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public bool IsActive { get; set; }
        public string GUID { get; set; }
        public string OwnedByOrgGUID { get; set; }
        public string TruckCapacityGUID { get; set; }
        public string CreatedByGUID { get; set; }
        public string ModifiedByGUID { get; set; }
    }
}
